import type {Metadata} from "next";
import "./globals.css";
import {Montserrat, Poppins} from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Hamsafar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={`${poppins.variable} ${montserrat.variable}`}>
      <body className="font-pop">
          <main>
              {children}
          </main>
      </body>
    </html>
  );
}
