import {
    AlertCircle, BarChart2, Bell, Coins, Cookie,
    CreditCard, DollarSign, FileText, Filter,
    HelpCircle, Languages, Layout,
    LayoutDashboard,
    List, Mail,
    NotebookText,
    Package, Search, Server, Settings, Share2,
    Sliders, TrendingUp, UserCheck,
    UserCog,
    Users, Video
} from "lucide-react";

export const roleMenuItems = [
    { id: "dashboard", title: "Dashboard", icon: LayoutDashboard, permissions: ["canView"] },
    { id: "members", title: "Members", icon: Users, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "profile_attributes", title: "Profile Attributes", icon: UserCog, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "payments", title: "Payments", icon: CreditCard, permissions: ["canView", "canCreate", "canEdit"] },
    { id: "frontend_settings", title: "Frontend Settings", icon: Sliders, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "faqs", title: "FAQs", icon: HelpCircle, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "faqs_category", title: "FAQs Category", icon: List, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "blogs", title: "Blogs", icon: NotebookText, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "blogs_category", title: "Blogs Category", icon: List, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "packages", title: "Packages", icon: Package, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "complaints", title: "Complaints", icon: AlertCircle, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "financial_report", title: "Financial Reports", icon: DollarSign, permissions: ["canView"] },
    { id: "income_report", title: "Income Reports", icon: TrendingUp, permissions: ["canView"] },
    { id: "detail_report", title: "Detail Reports", icon: TrendingUp, permissions: ["canView"] },
    { id: "member_report", title: "Member Report", icon: FileText, permissions: ["canView"] },
    { id: "newsletter", title: "Newsletter", icon: Mail, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "banners", title: "Banners", icon: Image, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "general_settings", title: "General Settings", icon: Settings, permissions: ["canView", "canEdit"] },
    { id: "preferences", title: "Preferences", icon: Sliders, permissions: ["canView","canEdit"] },
    { id: "analytic", title: "Analytic", icon: BarChart2, permissions: ["canView"] },
    { id: "seo_settings", title: "SEO Settings", icon: Search, permissions: ["canView", "canEdit"] },
    { id: "language", title: "Language", icon: Languages, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "currency", title: "Currency", icon: Coins, permissions: ["canView", "canEdit", "canCreate", "canDelete"] },
    { id: "payment_methods", title: "Payment Methods", icon: CreditCard, permissions: ["canView", "canEdit"] },
    { id: "smtp_settings", title: "SMTP Settings", icon: Mail, permissions: ["canView","canEdit"] },
    { id: "email_templates", title: "Email Templates", icon: Mail, permissions: ["canView","canEdit"] },
    { id: "third_party_settings", title: "Third Party Settings", icon: Settings, permissions: ["canView","canEdit"] },
    { id: "cookie", title: "Cookie", icon: Cookie, permissions: ["canView","canEdit"] },
    { id: "social_media_login", title: "Social Media Login", icon: Share2, permissions: ["canView","canEdit"] },
    { id: "abuse_word_filtering", title: "Abuse Word Filtering", icon: Filter, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "push_notification", title: "Push Notification", icon: Bell, permissions: ["canView","canEdit"] },
    { id: "staffs", title: "Staffs", icon: UserCheck, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "system", title: "System", icon: Server, permissions: ["canView"] },
    { id: "footer", title: "Footer", icon: Layout, permissions: ["canView", "canEdit"] },
    { id: "footer_section", title: "Footer Section", icon: Layout, permissions: ["canView", "canCreate", "canEdit", "canDelete"] },
    { id: "chat_video_setting", title: "Chat & Video Setting", icon: Video, permissions: ["canView", "canEdit"] }
] as const;

export const permissionTypes = [
    { key: "canView" as const, label: "view" },
    { key: "canCreate" as const, label: "create" },
    { key: "canEdit" as const, label: "edit" },
    { key: "canDelete" as const, label: "delete" },
];