import type {Metadata} from "next";
import "./globals.css";
import {Montserrat, Poppins} from "next/font/google";
import ClientProvider from "@/lib/client-provider";
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Hamsafar",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const session = await getServerSession(authOptions);

  return (
      <html lang="en" className={`${poppins.variable} ${montserrat.variable}`}>
      <body className="font-pop">
          <ClientProvider session={session}>
              <main>
                  {children}
              </main>
          </ClientProvider>
      </body>
    </html>
  );
}
