import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Poppins } from "next/font/google";
import ClientProvider from "@/lib/client-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import "../../i18n";
import TranslationsProvider from "@/shared-lib/translation-provider";
import { LanguageInitializer } from "@/lib/language-initializer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Hamsafar",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);
  console.error(session);

  return (
    <html lang="en" className={`${poppins.variable} ${montserrat.variable}`}>
      <body className="font-pop">
        <ClientProvider session={session}>
          <TranslationsProvider>
            <main>
               <LanguageInitializer /> 
              {children}
            </main>
          </TranslationsProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
