import {
  dashboardEnvelopIcon,
  dashboardLocationIcon,
  dashboardUserIcon,
} from "@/lib/icons";

export const matches = [
  {
    id: 1,
    name: "Donella",
    age: 28,
    location: "New York",
    image: "https://i.pravatar.cc/200?img=1",
    status: "online",
    account: "public",
  },
  {
    id: 2,
    name: "Naé",
    age: 25,
    location: "Los Angeles",
    image: "https://i.pravatar.cc/200?img=2",
    status: "offline",
    account: "private",
  },
  {
    id: 3,
    name: "Laura",
    age: 30,
    location: "Chicago",
    image: "https://i.pravatar.cc/200?img=3",
    status: "online",
    account: "plus",
  },
  {
    id: 4,
    name: "Daniella",
    age: 27,
    location: "Miami",
    image: "https://i.pravatar.cc/200?img=4",
    status: "online",
    account: "public",
  },
  {
    id: 5,
    name: "Noa",
    age: 24,
    location: "Seattle",
    image: "https://i.pravatar.cc/200?img=5",
    status: "offline",
    account: "public",
  },
  {
    id: 6,
    name: "Laura",
    age: 29,
    location: "Boston",
    image: "https://i.pravatar.cc/200?img=6",
    status: "online",
    account: "private",
  },
];

export const recentMembers = [
  {
    id: 7,
    name: "Donella",
    age: 26,
    location: "Denver",
    image: "https://i.pravatar.cc/200?img=7",
    status: "new",
    account: "plus",
  },
  {
    id: 8,
    name: "Naé",
    age: 23,
    location: "Portland",
    image: "https://i.pravatar.cc/200?img=8",
    status: "new",
    account: "private",
  },
  {
    id: 9,
    name: "Laura",
    age: 31,
    location: "Austin",
    image: "https://i.pravatar.cc/200?img=9",
    status: "new",
    account: "public",
  },
  {
    id: 10,
    name: "Daniella",
    age: 28,
    location: "Phoenix",
    image: "https://i.pravatar.cc/200?img=10",
    status: "new",
    account: "plus",
  },
  {
    id: 11,
    name: "Noa",
    age: 25,
    location: "San Diego",
    image: "https://i.pravatar.cc/200?img=11",
    status: "new",
    account: "public",
  },
  {
    id: 12,
    name: "Laura",
    age: 27,
    location: "Nashville",
    image: "https://i.pravatar.cc/200?img=12",
    status: "new",
    account: "public",
  },
];

export const cardData = [
  {
    icon: dashboardUserIcon,
    title: "My Username",
    value: "Demo",
  },
  {
    icon: dashboardLocationIcon,
    title: "My Location",
    value: "Mozambique",
  },
  {
    icon: dashboardEnvelopIcon,
    title: "My Email",
    value: "adsad@adsdas.com",
  },
];
